import type { ScoredCountry } from '../pipeline/types';

/**
 * Static border map: ISO3 -> array of bordering ISO3 codes.
 * Covers all countries with land borders. Island nations include
 * closest maritime neighbors for relevance.
 */
export const borderMap: Record<string, string[]> = {
  // Europe
  ALB: ['MNE', 'XKX', 'MKD', 'GRC'],
  AND: ['FRA', 'ESP'],
  AUT: ['DEU', 'CZE', 'SVK', 'HUN', 'SVN', 'ITA', 'CHE', 'LIE'],
  BEL: ['FRA', 'LUX', 'DEU', 'NLD'],
  BGR: ['ROU', 'SRB', 'MKD', 'GRC', 'TUR'],
  BIH: ['HRV', 'SRB', 'MNE'],
  BLR: ['POL', 'LTU', 'LVA', 'RUS', 'UKR'],
  CHE: ['DEU', 'FRA', 'ITA', 'AUT', 'LIE'],
  CYP: ['TUR', 'GRC'],
  CZE: ['DEU', 'POL', 'SVK', 'AUT'],
  DEU: ['DNK', 'POL', 'CZE', 'AUT', 'CHE', 'FRA', 'LUX', 'BEL', 'NLD'],
  DNK: ['DEU'],
  ESP: ['FRA', 'PRT', 'AND', 'MAR'],
  EST: ['LVA', 'RUS', 'FIN'],
  FIN: ['SWE', 'NOR', 'RUS', 'EST'],
  FRA: ['BEL', 'LUX', 'DEU', 'CHE', 'ITA', 'ESP', 'AND', 'MCO'],
  GBR: ['IRL', 'FRA'],
  GEO: ['RUS', 'TUR', 'ARM', 'AZE'],
  GRC: ['ALB', 'MKD', 'BGR', 'TUR', 'CYP'],
  HRV: ['SVN', 'HUN', 'SRB', 'BIH', 'MNE'],
  HUN: ['AUT', 'SVK', 'UKR', 'ROU', 'SRB', 'HRV', 'SVN'],
  IRL: ['GBR'],
  ISL: ['GBR', 'NOR'],
  ITA: ['FRA', 'CHE', 'AUT', 'SVN', 'SMR', 'VAT'],
  LIE: ['CHE', 'AUT'],
  LTU: ['LVA', 'BLR', 'POL', 'RUS'],
  LUX: ['BEL', 'FRA', 'DEU'],
  LVA: ['EST', 'LTU', 'BLR', 'RUS'],
  MCO: ['FRA'],
  MDA: ['ROU', 'UKR'],
  MKD: ['ALB', 'GRC', 'BGR', 'SRB', 'XKX'],
  MLT: ['ITA'],
  MNE: ['HRV', 'BIH', 'SRB', 'XKX', 'ALB'],
  NLD: ['BEL', 'DEU'],
  NOR: ['SWE', 'FIN', 'RUS'],
  POL: ['DEU', 'CZE', 'SVK', 'UKR', 'BLR', 'LTU', 'RUS'],
  PRT: ['ESP'],
  ROU: ['HUN', 'SRB', 'BGR', 'MDA', 'UKR'],
  SMR: ['ITA'],
  SRB: ['HUN', 'ROU', 'BGR', 'MKD', 'XKX', 'MNE', 'BIH', 'HRV'],
  SVK: ['CZE', 'POL', 'UKR', 'HUN', 'AUT'],
  SVN: ['ITA', 'AUT', 'HUN', 'HRV'],
  SWE: ['NOR', 'FIN'],
  UKR: ['POL', 'SVK', 'HUN', 'ROU', 'MDA', 'BLR', 'RUS'],
  XKX: ['SRB', 'MNE', 'ALB', 'MKD'],
  VAT: ['ITA'],

  // Middle East
  ARE: ['OMN', 'SAU'],
  ARM: ['GEO', 'AZE', 'TUR', 'IRN'],
  AZE: ['GEO', 'ARM', 'TUR', 'IRN', 'RUS'],
  BHR: ['SAU', 'QAT'],
  IRN: ['IRQ', 'TUR', 'ARM', 'AZE', 'TKM', 'AFG', 'PAK'],
  IRQ: ['TUR', 'IRN', 'KWT', 'SAU', 'JOR', 'SYR'],
  ISR: ['LBN', 'SYR', 'JOR', 'EGY', 'PSE'],
  JOR: ['SYR', 'IRQ', 'SAU', 'ISR', 'PSE'],
  KWT: ['IRQ', 'SAU'],
  LBN: ['SYR', 'ISR'],
  OMN: ['ARE', 'SAU', 'YEM'],
  PSE: ['ISR', 'EGY', 'JOR'],
  QAT: ['SAU', 'BHR'],
  SAU: ['JOR', 'IRQ', 'KWT', 'BHR', 'QAT', 'ARE', 'OMN', 'YEM'],
  SYR: ['TUR', 'IRQ', 'JOR', 'ISR', 'LBN'],
  TUR: ['GRC', 'BGR', 'GEO', 'ARM', 'AZE', 'IRN', 'IRQ', 'SYR'],
  YEM: ['SAU', 'OMN'],

  // Asia
  AFG: ['PAK', 'IRN', 'TKM', 'UZB', 'TJK', 'CHN'],
  BGD: ['IND', 'MMR'],
  BTN: ['IND', 'CHN'],
  BRN: ['MYS'],
  KHM: ['THA', 'LAO', 'VNM'],
  CHN: ['RUS', 'MNG', 'PRK', 'VNM', 'LAO', 'MMR', 'IND', 'BTN', 'NPL', 'PAK', 'AFG', 'TJK', 'KGZ', 'KAZ'],
  IND: ['PAK', 'CHN', 'NPL', 'BTN', 'BGD', 'MMR', 'LKA'],
  IDN: ['MYS', 'PNG', 'TLS'],
  JPN: ['KOR', 'CHN', 'RUS'],
  KAZ: ['RUS', 'CHN', 'KGZ', 'UZB', 'TKM'],
  KGZ: ['KAZ', 'CHN', 'TJK', 'UZB'],
  LAO: ['CHN', 'VNM', 'KHM', 'THA', 'MMR'],
  MYS: ['THA', 'IDN', 'BRN', 'SGP'],
  MDV: ['IND', 'LKA'],
  MNG: ['RUS', 'CHN'],
  MMR: ['CHN', 'IND', 'BGD', 'LAO', 'THA'],
  NPL: ['IND', 'CHN'],
  PRK: ['CHN', 'KOR', 'RUS'],
  KOR: ['PRK', 'JPN'],
  PAK: ['IND', 'CHN', 'AFG', 'IRN'],
  PHL: ['TWN', 'IDN', 'MYS'],
  SGP: ['MYS', 'IDN'],
  LKA: ['IND', 'MDV'],
  TWN: ['CHN', 'JPN', 'PHL'],
  TJK: ['KGZ', 'CHN', 'AFG', 'UZB'],
  THA: ['MMR', 'LAO', 'KHM', 'MYS'],
  TLS: ['IDN'],
  TKM: ['KAZ', 'UZB', 'AFG', 'IRN'],
  UZB: ['KAZ', 'KGZ', 'TJK', 'AFG', 'TKM'],
  VNM: ['CHN', 'LAO', 'KHM'],
  HKG: ['CHN'],
  MAC: ['CHN'],

  // Africa
  DZA: ['MAR', 'TUN', 'LBY', 'NER', 'MLI', 'MRT'],
  AGO: ['COD', 'COG', 'ZMB', 'NAM'],
  BEN: ['TGO', 'BFA', 'NER', 'NGA'],
  BWA: ['ZAF', 'NAM', 'ZMB', 'ZWE'],
  BFA: ['MLI', 'NER', 'BEN', 'TGO', 'GHA', 'CIV'],
  BDI: ['COD', 'RWA', 'TZA'],
  CPV: ['SEN', 'GMB'],
  CMR: ['NGA', 'TCD', 'CAF', 'COG', 'GAB', 'GNQ'],
  CAF: ['TCD', 'SDN', 'SSD', 'COD', 'COG', 'CMR'],
  TCD: ['LBY', 'SDN', 'CAF', 'CMR', 'NGA', 'NER'],
  COM: ['MDG', 'MOZ'],
  COG: ['GAB', 'CMR', 'CAF', 'COD', 'AGO'],
  COD: ['COG', 'CAF', 'SSD', 'UGA', 'RWA', 'BDI', 'TZA', 'ZMB', 'AGO'],
  CIV: ['LBR', 'GIN', 'MLI', 'BFA', 'GHA'],
  DJI: ['ERI', 'ETH', 'SOM'],
  EGY: ['LBY', 'SDN', 'ISR', 'PSE'],
  GNQ: ['CMR', 'GAB'],
  ERI: ['SDN', 'ETH', 'DJI'],
  SWZ: ['ZAF', 'MOZ'],
  ETH: ['ERI', 'DJI', 'SOM', 'KEN', 'SSD', 'SDN'],
  GAB: ['CMR', 'GNQ', 'COG'],
  GMB: ['SEN'],
  GHA: ['CIV', 'BFA', 'TGO'],
  GIN: ['GNB', 'SEN', 'MLI', 'CIV', 'LBR', 'SLE'],
  GNB: ['SEN', 'GIN'],
  KEN: ['ETH', 'SOM', 'TZA', 'UGA', 'SSD'],
  LSO: ['ZAF'],
  LBR: ['GIN', 'CIV', 'SLE'],
  LBY: ['TUN', 'DZA', 'NER', 'TCD', 'SDN', 'EGY'],
  MDG: ['MOZ', 'COM'],
  MWI: ['MOZ', 'TZA', 'ZMB'],
  MLI: ['DZA', 'NER', 'BFA', 'CIV', 'GIN', 'SEN', 'MRT'],
  MRT: ['DZA', 'MLI', 'SEN'],
  MUS: ['MDG'],
  MAR: ['DZA', 'ESP', 'MRT'],
  MOZ: ['ZAF', 'SWZ', 'ZWE', 'ZMB', 'MWI', 'TZA'],
  NAM: ['AGO', 'ZMB', 'BWA', 'ZAF'],
  NER: ['DZA', 'LBY', 'TCD', 'NGA', 'BEN', 'BFA', 'MLI'],
  NGA: ['BEN', 'NER', 'TCD', 'CMR'],
  RWA: ['UGA', 'TZA', 'BDI', 'COD'],
  STP: ['GAB', 'GNQ'],
  SEN: ['MRT', 'MLI', 'GIN', 'GNB', 'GMB'],
  SYC: ['MDG', 'MUS'],
  SLE: ['GIN', 'LBR'],
  SOM: ['ETH', 'DJI', 'KEN'],
  ZAF: ['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO'],
  SSD: ['SDN', 'ETH', 'KEN', 'UGA', 'COD', 'CAF'],
  SDN: ['EGY', 'LBY', 'TCD', 'CAF', 'SSD', 'ETH', 'ERI'],
  TZA: ['KEN', 'UGA', 'RWA', 'BDI', 'COD', 'ZMB', 'MWI', 'MOZ'],
  TGO: ['GHA', 'BFA', 'BEN'],
  TUN: ['DZA', 'LBY'],
  UGA: ['KEN', 'TZA', 'RWA', 'COD', 'SSD'],
  ZMB: ['COD', 'TZA', 'MWI', 'MOZ', 'ZWE', 'BWA', 'NAM', 'AGO'],
  ZWE: ['ZAF', 'BWA', 'ZMB', 'MOZ'],

  // Americas
  ARG: ['CHL', 'BOL', 'PRY', 'BRA', 'URY'],
  BLZ: ['MEX', 'GTM'],
  BOL: ['BRA', 'PRY', 'ARG', 'CHL', 'PER'],
  BRA: ['GUY', 'SUR', 'VEN', 'COL', 'PER', 'BOL', 'PRY', 'ARG', 'URY'],
  CAN: ['USA'],
  CHL: ['PER', 'BOL', 'ARG'],
  COL: ['VEN', 'BRA', 'PER', 'ECU', 'PAN'],
  CRI: ['NIC', 'PAN'],
  CUB: ['USA', 'MEX', 'JAM'],
  DOM: ['HTI'],
  ECU: ['COL', 'PER'],
  SLV: ['GTM', 'HND'],
  GTM: ['MEX', 'BLZ', 'SLV', 'HND'],
  GUY: ['VEN', 'BRA', 'SUR'],
  HTI: ['DOM'],
  HND: ['GTM', 'SLV', 'NIC'],
  JAM: ['CUB', 'HTI'],
  MEX: ['USA', 'GTM', 'BLZ'],
  NIC: ['HND', 'CRI'],
  PAN: ['CRI', 'COL'],
  PRY: ['BOL', 'BRA', 'ARG'],
  PER: ['ECU', 'COL', 'BRA', 'BOL', 'CHL'],
  SUR: ['GUY', 'BRA'],
  TTO: ['VEN'],
  USA: ['CAN', 'MEX'],
  URY: ['BRA', 'ARG'],
  VEN: ['COL', 'BRA', 'GUY', 'TTO'],

  // Caribbean islands (maritime neighbors)
  ATG: ['KNA', 'DMA'],
  BHS: ['USA', 'CUB'],
  BRB: ['VCT', 'LCA', 'TTO'],
  DMA: ['ATG', 'LCA'],
  GRD: ['VCT', 'TTO'],
  KNA: ['ATG'],
  LCA: ['DMA', 'VCT', 'BRB'],
  VCT: ['LCA', 'GRD', 'BRB'],

  // Oceania
  AUS: ['NZL', 'IDN', 'PNG'],
  FJI: ['TON', 'VUT', 'WSM'],
  KIR: ['MHL', 'NRU'],
  MHL: ['KIR', 'FSM'],
  FSM: ['MHL', 'PLW'],
  NRU: ['KIR'],
  NZL: ['AUS', 'FJI'],
  PLW: ['FSM', 'PHL'],
  PNG: ['IDN', 'AUS', 'SLB'],
  WSM: ['FJI', 'TON'],
  SLB: ['PNG', 'VUT'],
  TON: ['FJI', 'WSM'],
  TUV: ['FJI', 'KIR'],
  VUT: ['FJI', 'SLB'],

  // Russia (special case - borders many)
  RUS: ['NOR', 'FIN', 'EST', 'LVA', 'LTU', 'POL', 'BLR', 'UKR', 'GEO', 'AZE', 'KAZ', 'CHN', 'MNG', 'PRK'],
};

/**
 * Get neighboring countries with their full scored data.
 * Returns ScoredCountry objects sorted by score descending, max 6.
 */
export function getNeighbors(iso3: string, allCountries: ScoredCountry[]): ScoredCountry[] {
  const borders = borderMap[iso3];
  if (!borders || borders.length === 0) return [];

  const borderSet = new Set(borders);
  const countryMap = new Map(allCountries.map(c => [c.iso3, c]));

  return borders
    .filter(b => countryMap.has(b))
    .map(b => countryMap.get(b)!)
    .sort((a, b) => b.score - a.score)
    .slice(0, 6);
}
