import type { CountryEntry } from '../types.js';

export const COUNTRIES: CountryEntry[] = [
  { iso3: 'AFG', iso2: 'AF', name: { en: 'Afghanistan', it: 'Afghanistan', es: 'Afganistán', fr: 'Afghanistan', pt: 'Afeganistão' } },
  { iso3: 'ALB', iso2: 'AL', name: { en: 'Albania', it: 'Albania', es: 'Albania', fr: 'Albanie', pt: 'Albânia' } },
  { iso3: 'DZA', iso2: 'DZ', name: { en: 'Algeria', it: 'Algeria', es: 'Argelia', fr: 'Algérie', pt: 'Argélia' } },
  { iso3: 'AND', iso2: 'AD', name: { en: 'Andorra', it: 'Andorra', es: 'Andorra', fr: 'Andorre', pt: 'Andorra' } },
  { iso3: 'AGO', iso2: 'AO', name: { en: 'Angola', it: 'Angola', es: 'Angola', fr: 'Angola', pt: 'Angola' } },
  { iso3: 'ATG', iso2: 'AG', name: { en: 'Antigua and Barbuda', it: 'Antigua e Barbuda', es: 'Antigua y Barbuda', fr: 'Antigua-et-Barbuda', pt: 'Antigua e Barbuda' } },
  { iso3: 'ARG', iso2: 'AR', name: { en: 'Argentina', it: 'Argentina', es: 'Argentina', fr: 'Argentine', pt: 'Argentina' } },
  { iso3: 'ARM', iso2: 'AM', name: { en: 'Armenia', it: 'Armenia', es: 'Armenia', fr: 'Arménie', pt: 'Armênia' } },
  { iso3: 'AUS', iso2: 'AU', name: { en: 'Australia', it: 'Australia', es: 'Australia', fr: 'Australie', pt: 'Austrália' } },
  { iso3: 'AUT', iso2: 'AT', name: { en: 'Austria', it: 'Austria', es: 'Austria', fr: 'Autriche', pt: 'Áustria' } },
  { iso3: 'AZE', iso2: 'AZ', name: { en: 'Azerbaijan', it: 'Azerbaigian', es: 'Azerbaiyán', fr: 'Azerbaïdjan', pt: 'Azerbaijão' } },
  { iso3: 'BHS', iso2: 'BS', name: { en: 'Bahamas', it: 'Bahamas', es: 'Bahamas', fr: 'Bahamas', pt: 'Bahamas' } },
  { iso3: 'BHR', iso2: 'BH', name: { en: 'Bahrain', it: 'Bahrein', es: 'Baréin', fr: 'Bahreïn', pt: 'Barein' } },
  { iso3: 'BGD', iso2: 'BD', name: { en: 'Bangladesh', it: 'Bangladesh', es: 'Bangladesh', fr: 'Bangladesh', pt: 'Bangladesh' } },
  { iso3: 'BRB', iso2: 'BB', name: { en: 'Barbados', it: 'Barbados', es: 'Barbados', fr: 'Barbade', pt: 'Barbados' } },
  { iso3: 'BLR', iso2: 'BY', name: { en: 'Belarus', it: 'Bielorussia', es: 'Bielorrusia', fr: 'Biélorussie', pt: 'Bielorrússia' } },
  { iso3: 'BEL', iso2: 'BE', name: { en: 'Belgium', it: 'Belgio', es: 'Bélgica', fr: 'Belgique', pt: 'Bélgica' } },
  { iso3: 'BLZ', iso2: 'BZ', name: { en: 'Belize', it: 'Belize', es: 'Belice', fr: 'Belize', pt: 'Belize' } },
  { iso3: 'BEN', iso2: 'BJ', name: { en: 'Benin', it: 'Benin', es: 'Benin', fr: 'Bénin', pt: 'Benim' } },
  { iso3: 'BTN', iso2: 'BT', name: { en: 'Bhutan', it: 'Bhutan', es: 'Bután', fr: 'Bhoutan', pt: 'Butão' } },
  { iso3: 'BOL', iso2: 'BO', name: { en: 'Bolivia', it: 'Bolivia', es: 'Bolivia', fr: 'Bolivie', pt: 'Bolívia' } },
  { iso3: 'BIH', iso2: 'BA', name: { en: 'Bosnia and Herzegovina', it: 'Bosnia ed Erzegovina', es: 'Bosnia y Herzegovina', fr: 'Bosnie-Herzégovine', pt: 'Bósnia e Herzegovina' } },
  { iso3: 'BWA', iso2: 'BW', name: { en: 'Botswana', it: 'Botswana', es: 'Botsuana', fr: 'Botswana', pt: 'Botsuana' } },
  { iso3: 'BRA', iso2: 'BR', name: { en: 'Brazil', it: 'Brasile', es: 'Brasil', fr: 'Brésil', pt: 'Brasil' } },
  { iso3: 'BRN', iso2: 'BN', name: { en: 'Brunei', it: 'Brunei', es: 'Brunei', fr: 'Brunei', pt: 'Brunei' } },
  { iso3: 'BGR', iso2: 'BG', name: { en: 'Bulgaria', it: 'Bulgaria', es: 'Bulgaria', fr: 'Bulgarie', pt: 'Bulgária' } },
  { iso3: 'BFA', iso2: 'BF', name: { en: 'Burkina Faso', it: 'Burkina Faso', es: 'Burkina Faso', fr: 'Burkina Faso', pt: 'Burquina Faso' } },
  { iso3: 'BDI', iso2: 'BI', name: { en: 'Burundi', it: 'Burundi', es: 'Burundi', fr: 'Burundi', pt: 'Burundi' } },
  { iso3: 'CPV', iso2: 'CV', name: { en: 'Cabo Verde', it: 'Capo Verde', es: 'Cabo Verde', fr: 'Cap-Vert', pt: 'Cabo Verde' } },
  { iso3: 'KHM', iso2: 'KH', name: { en: 'Cambodia', it: 'Cambogia', es: 'Camboya', fr: 'Cambodge', pt: 'Camboja' } },
  { iso3: 'CMR', iso2: 'CM', name: { en: 'Cameroon', it: 'Camerun', es: 'Camerún', fr: 'Cameroun', pt: 'Camarões' } },
  { iso3: 'CAN', iso2: 'CA', name: { en: 'Canada', it: 'Canada', es: 'Canadá', fr: 'Canada', pt: 'Canadá' } },
  { iso3: 'CAF', iso2: 'CF', name: { en: 'Central African Republic', it: 'Repubblica Centrafricana', es: 'República Centroafricana', fr: 'République centrafricaine', pt: 'República Centro-Africana' } },
  { iso3: 'TCD', iso2: 'TD', name: { en: 'Chad', it: 'Ciad', es: 'Chad', fr: 'Tchad', pt: 'Chade' } },
  { iso3: 'CHL', iso2: 'CL', name: { en: 'Chile', it: 'Cile', es: 'Chile', fr: 'Chili', pt: 'Chile' } },
  { iso3: 'CHN', iso2: 'CN', name: { en: 'China', it: 'Cina', es: 'China', fr: 'Chine', pt: 'China' } },
  { iso3: 'COL', iso2: 'CO', name: { en: 'Colombia', it: 'Colombia', es: 'Colombia', fr: 'Colombie', pt: 'Colômbia' } },
  { iso3: 'COM', iso2: 'KM', name: { en: 'Comoros', it: 'Comore', es: 'Comoras', fr: 'Comores', pt: 'Comores' } },
  { iso3: 'COG', iso2: 'CG', name: { en: 'Congo', it: 'Congo', es: 'Congo', fr: 'Congo', pt: 'Congo' } },
  { iso3: 'COD', iso2: 'CD', name: { en: 'Democratic Republic of the Congo', it: 'Repubblica Democratica del Congo', es: 'República Democrática del Congo', fr: 'République démocratique du Congo', pt: 'República Democrática do Congo' } },
  { iso3: 'CRI', iso2: 'CR', name: { en: 'Costa Rica', it: 'Costa Rica', es: 'Costa Rica', fr: 'Costa Rica', pt: 'Costa Rica' } },
  { iso3: 'CIV', iso2: 'CI', name: { en: "Cote d'Ivoire", it: "Costa d'Avorio", es: "Costa de Marfil", fr: "Cote d'Ivoire", pt: 'Costa do Marfim' } },
  { iso3: 'HRV', iso2: 'HR', name: { en: 'Croatia', it: 'Croazia', es: 'Croacia', fr: 'Croatie', pt: 'Croácia' } },
  { iso3: 'CUB', iso2: 'CU', name: { en: 'Cuba', it: 'Cuba', es: 'Cuba', fr: 'Cuba', pt: 'Cuba' } },
  { iso3: 'CYP', iso2: 'CY', name: { en: 'Cyprus', it: 'Cipro', es: 'Chipre', fr: 'Chypre', pt: 'Chipre' } },
  { iso3: 'CZE', iso2: 'CZ', name: { en: 'Czech Republic', it: 'Repubblica Ceca', es: 'República Checa', fr: 'République tchèque', pt: 'República Tcheca' } },
  { iso3: 'DNK', iso2: 'DK', name: { en: 'Denmark', it: 'Danimarca', es: 'Dinamarca', fr: 'Danemark', pt: 'Dinamarca' } },
  { iso3: 'DJI', iso2: 'DJ', name: { en: 'Djibouti', it: 'Gibuti', es: 'Yibuti', fr: 'Djibouti', pt: 'Djibuti' } },
  { iso3: 'DMA', iso2: 'DM', name: { en: 'Dominica', it: 'Dominica', es: 'Dominica', fr: 'Dominique', pt: 'Dominica' } },
  { iso3: 'DOM', iso2: 'DO', name: { en: 'Dominican Republic', it: 'Repubblica Dominicana', es: 'República Dominicana', fr: 'République dominicaine', pt: 'República Dominicana' } },
  { iso3: 'ECU', iso2: 'EC', name: { en: 'Ecuador', it: 'Ecuador', es: 'Ecuador', fr: 'Équateur', pt: 'Equador' } },
  { iso3: 'EGY', iso2: 'EG', name: { en: 'Egypt', it: 'Egitto', es: 'Egipto', fr: 'Égypte', pt: 'Egito' } },
  { iso3: 'SLV', iso2: 'SV', name: { en: 'El Salvador', it: 'El Salvador', es: 'El Salvador', fr: 'El Salvador', pt: 'El Salvador' } },
  { iso3: 'GNQ', iso2: 'GQ', name: { en: 'Equatorial Guinea', it: 'Guinea Equatoriale', es: 'Guinea Ecuatorial', fr: 'Guinée équatoriale', pt: 'Guiné Equatorial' } },
  { iso3: 'ERI', iso2: 'ER', name: { en: 'Eritrea', it: 'Eritrea', es: 'Eritrea', fr: 'Érythrée', pt: 'Eritreia' } },
  { iso3: 'EST', iso2: 'EE', name: { en: 'Estonia', it: 'Estonia', es: 'Estonia', fr: 'Estonie', pt: 'Estônia' } },
  { iso3: 'SWZ', iso2: 'SZ', name: { en: 'Eswatini', it: 'Eswatini', es: 'Esuatini', fr: 'Eswatini', pt: 'Eswatini' } },
  { iso3: 'ETH', iso2: 'ET', name: { en: 'Ethiopia', it: 'Etiopia', es: 'Etiopía', fr: 'Éthiopie', pt: 'Etiópia' } },
  { iso3: 'FJI', iso2: 'FJ', name: { en: 'Fiji', it: 'Figi', es: 'Fiyi', fr: 'Fidji', pt: 'Fiji' } },
  { iso3: 'FIN', iso2: 'FI', name: { en: 'Finland', it: 'Finlandia', es: 'Finlandia', fr: 'Finlande', pt: 'Finlândia' } },
  { iso3: 'FRA', iso2: 'FR', name: { en: 'France', it: 'Francia', es: 'Francia', fr: 'France', pt: 'França' } },
  { iso3: 'GAB', iso2: 'GA', name: { en: 'Gabon', it: 'Gabon', es: 'Gabón', fr: 'Gabon', pt: 'Gabão' } },
  { iso3: 'GMB', iso2: 'GM', name: { en: 'Gambia', it: 'Gambia', es: 'Gambia', fr: 'Gambie', pt: 'Gâmbia' } },
  { iso3: 'GEO', iso2: 'GE', name: { en: 'Georgia', it: 'Georgia', es: 'Georgia', fr: 'Géorgie', pt: 'Geórgia' } },
  { iso3: 'DEU', iso2: 'DE', name: { en: 'Germany', it: 'Germania', es: 'Alemania', fr: 'Allemagne', pt: 'Alemanha' } },
  { iso3: 'GHA', iso2: 'GH', name: { en: 'Ghana', it: 'Ghana', es: 'Ghana', fr: 'Ghana', pt: 'Gana' } },
  { iso3: 'GRC', iso2: 'GR', name: { en: 'Greece', it: 'Grecia', es: 'Grecia', fr: 'Grèce', pt: 'Grécia' } },
  { iso3: 'GRD', iso2: 'GD', name: { en: 'Grenada', it: 'Grenada', es: 'Granada', fr: 'Grenade', pt: 'Granada' } },
  { iso3: 'GTM', iso2: 'GT', name: { en: 'Guatemala', it: 'Guatemala', es: 'Guatemala', fr: 'Guatemala', pt: 'Guatemala' } },
  { iso3: 'GIN', iso2: 'GN', name: { en: 'Guinea', it: 'Guinea', es: 'Guinea', fr: 'Guinée', pt: 'Guiné' } },
  { iso3: 'GNB', iso2: 'GW', name: { en: 'Guinea-Bissau', it: 'Guinea-Bissau', es: 'Guinea-Bisáu', fr: 'Guinée-Bissau', pt: 'Guiné-Bissau' } },
  { iso3: 'GUY', iso2: 'GY', name: { en: 'Guyana', it: 'Guyana', es: 'Guyana', fr: 'Guyana', pt: 'Guiana' } },
  { iso3: 'HTI', iso2: 'HT', name: { en: 'Haiti', it: 'Haiti', es: 'Haití', fr: 'Haïti', pt: 'Haiti' } },
  { iso3: 'HND', iso2: 'HN', name: { en: 'Honduras', it: 'Honduras', es: 'Honduras', fr: 'Honduras', pt: 'Honduras' } },
  { iso3: 'HUN', iso2: 'HU', name: { en: 'Hungary', it: 'Ungheria', es: 'Hungría', fr: 'Hongrie', pt: 'Hungria' } },
  { iso3: 'ISL', iso2: 'IS', name: { en: 'Iceland', it: 'Islanda', es: 'Islandia', fr: 'Islande', pt: 'Islândia' } },
  { iso3: 'IND', iso2: 'IN', name: { en: 'India', it: 'India', es: 'India', fr: 'Inde', pt: 'Índia' } },
  { iso3: 'IDN', iso2: 'ID', name: { en: 'Indonesia', it: 'Indonesia', es: 'Indonesia', fr: 'Indonésie', pt: 'Indonésia' } },
  { iso3: 'IRN', iso2: 'IR', name: { en: 'Iran', it: 'Iran', es: 'Irán', fr: 'Iran', pt: 'Irã' } },
  { iso3: 'IRQ', iso2: 'IQ', name: { en: 'Iraq', it: 'Iraq', es: 'Irak', fr: 'Irak', pt: 'Iraque' } },
  { iso3: 'IRL', iso2: 'IE', name: { en: 'Ireland', it: 'Irlanda', es: 'Irlanda', fr: 'Irlande', pt: 'Irlanda' } },
  { iso3: 'ISR', iso2: 'IL', name: { en: 'Israel', it: 'Israele', es: 'Israel', fr: 'Israël', pt: 'Israel' } },
  { iso3: 'ITA', iso2: 'IT', name: { en: 'Italy', it: 'Italia', es: 'Italia', fr: 'Italie', pt: 'Itália' } },
  { iso3: 'JAM', iso2: 'JM', name: { en: 'Jamaica', it: 'Giamaica', es: 'Jamaica', fr: 'Jamaïque', pt: 'Jamaica' } },
  { iso3: 'JPN', iso2: 'JP', name: { en: 'Japan', it: 'Giappone', es: 'Japón', fr: 'Japon', pt: 'Japão' } },
  { iso3: 'JOR', iso2: 'JO', name: { en: 'Jordan', it: 'Giordania', es: 'Jordania', fr: 'Jordanie', pt: 'Jordânia' } },
  { iso3: 'KAZ', iso2: 'KZ', name: { en: 'Kazakhstan', it: 'Kazakistan', es: 'Kazajistán', fr: 'Kazakhstan', pt: 'Cazaquistão' } },
  { iso3: 'KEN', iso2: 'KE', name: { en: 'Kenya', it: 'Kenya', es: 'Kenia', fr: 'Kenya', pt: 'Quênia' } },
  { iso3: 'KIR', iso2: 'KI', name: { en: 'Kiribati', it: 'Kiribati', es: 'Kiribati', fr: 'Kiribati', pt: 'Kiribati' } },
  { iso3: 'PRK', iso2: 'KP', name: { en: 'North Korea', it: 'Corea del Nord', es: 'Corea del Norte', fr: 'Corée du Nord', pt: 'Coreia do Norte' } },
  { iso3: 'KOR', iso2: 'KR', name: { en: 'South Korea', it: 'Corea del Sud', es: 'Corea del Sur', fr: 'Corée du Sud', pt: 'Coreia do Sul' } },
  { iso3: 'KWT', iso2: 'KW', name: { en: 'Kuwait', it: 'Kuwait', es: 'Kuwait', fr: 'Koweït', pt: 'Kuwait' } },
  { iso3: 'KGZ', iso2: 'KG', name: { en: 'Kyrgyzstan', it: 'Kirghizistan', es: 'Kirguistán', fr: 'Kirghizistan', pt: 'Quirguistão' } },
  { iso3: 'LAO', iso2: 'LA', name: { en: 'Laos', it: 'Laos', es: 'Laos', fr: 'Laos', pt: 'Laos' } },
  { iso3: 'LVA', iso2: 'LV', name: { en: 'Latvia', it: 'Lettonia', es: 'Letonia', fr: 'Lettonie', pt: 'Letônia' } },
  { iso3: 'LBN', iso2: 'LB', name: { en: 'Lebanon', it: 'Libano', es: 'Líbano', fr: 'Liban', pt: 'Líbano' } },
  { iso3: 'LSO', iso2: 'LS', name: { en: 'Lesotho', it: 'Lesotho', es: 'Lesoto', fr: 'Lesotho', pt: 'Lesoto' } },
  { iso3: 'LBR', iso2: 'LR', name: { en: 'Liberia', it: 'Liberia', es: 'Liberia', fr: 'Liberia', pt: 'Libéria' } },
  { iso3: 'LBY', iso2: 'LY', name: { en: 'Libya', it: 'Libia', es: 'Libia', fr: 'Libye', pt: 'Líbia' } },
  { iso3: 'LIE', iso2: 'LI', name: { en: 'Liechtenstein', it: 'Liechtenstein', es: 'Liechtenstein', fr: 'Liechtenstein', pt: 'Liechtenstein' } },
  { iso3: 'LTU', iso2: 'LT', name: { en: 'Lithuania', it: 'Lituania', es: 'Lituania', fr: 'Lituanie', pt: 'Lituânia' } },
  { iso3: 'LUX', iso2: 'LU', name: { en: 'Luxembourg', it: 'Lussemburgo', es: 'Luxemburgo', fr: 'Luxembourg', pt: 'Luxemburgo' } },
  { iso3: 'MDG', iso2: 'MG', name: { en: 'Madagascar', it: 'Madagascar', es: 'Madagascar', fr: 'Madagascar', pt: 'Madagascar' } },
  { iso3: 'MWI', iso2: 'MW', name: { en: 'Malawi', it: 'Malawi', es: 'Malaui', fr: 'Malawi', pt: 'Malawi' } },
  { iso3: 'MYS', iso2: 'MY', name: { en: 'Malaysia', it: 'Malesia', es: 'Malasia', fr: 'Malaisie', pt: 'Malásia' } },
  { iso3: 'MDV', iso2: 'MV', name: { en: 'Maldives', it: 'Maldive', es: 'Maldivas', fr: 'Maldives', pt: 'Maldivas' } },
  { iso3: 'MLI', iso2: 'ML', name: { en: 'Mali', it: 'Mali', es: 'Malí', fr: 'Mali', pt: 'Mali' } },
  { iso3: 'MLT', iso2: 'MT', name: { en: 'Malta', it: 'Malta', es: 'Malta', fr: 'Malte', pt: 'Malta' } },
  { iso3: 'MHL', iso2: 'MH', name: { en: 'Marshall Islands', it: 'Isole Marshall', es: 'Islas Marshall', fr: 'Îles Marshall', pt: 'Ilhas Marshall' } },
  { iso3: 'MRT', iso2: 'MR', name: { en: 'Mauritania', it: 'Mauritania', es: 'Mauritania', fr: 'Mauritanie', pt: 'Mauritânia' } },
  { iso3: 'MUS', iso2: 'MU', name: { en: 'Mauritius', it: 'Mauritius', es: 'Mauricio', fr: 'Maurice', pt: 'Maurício' } },
  { iso3: 'MEX', iso2: 'MX', name: { en: 'Mexico', it: 'Messico', es: 'México', fr: 'Mexique', pt: 'México' } },
  { iso3: 'FSM', iso2: 'FM', name: { en: 'Micronesia', it: 'Micronesia', es: 'Micronesia', fr: 'Micronésie', pt: 'Micronésia' } },
  { iso3: 'MDA', iso2: 'MD', name: { en: 'Moldova', it: 'Moldavia', es: 'Moldavia', fr: 'Moldavie', pt: 'Moldávia' } },
  { iso3: 'MCO', iso2: 'MC', name: { en: 'Monaco', it: 'Monaco', es: 'Mónaco', fr: 'Monaco', pt: 'Mônaco' } },
  { iso3: 'MNG', iso2: 'MN', name: { en: 'Mongolia', it: 'Mongolia', es: 'Mongolia', fr: 'Mongolie', pt: 'Mongólia' } },
  { iso3: 'MNE', iso2: 'ME', name: { en: 'Montenegro', it: 'Montenegro', es: 'Montenegro', fr: 'Monténégro', pt: 'Montenegro' } },
  { iso3: 'MAR', iso2: 'MA', name: { en: 'Morocco', it: 'Marocco', es: 'Marruecos', fr: 'Maroc', pt: 'Marrocos' } },
  { iso3: 'MOZ', iso2: 'MZ', name: { en: 'Mozambique', it: 'Mozambico', es: 'Mozambique', fr: 'Mozambique', pt: 'Moçambique' } },
  { iso3: 'MMR', iso2: 'MM', name: { en: 'Myanmar', it: 'Myanmar', es: 'Myanmar', fr: 'Birmanie', pt: 'Mianmar' } },
  { iso3: 'NAM', iso2: 'NA', name: { en: 'Namibia', it: 'Namibia', es: 'Namibia', fr: 'Namibie', pt: 'Namíbia' } },
  { iso3: 'NRU', iso2: 'NR', name: { en: 'Nauru', it: 'Nauru', es: 'Nauru', fr: 'Nauru', pt: 'Nauru' } },
  { iso3: 'NPL', iso2: 'NP', name: { en: 'Nepal', it: 'Nepal', es: 'Nepal', fr: 'Nepal', pt: 'Nepal' } },
  { iso3: 'NLD', iso2: 'NL', name: { en: 'Netherlands', it: 'Paesi Bassi', es: 'Países Bajos', fr: 'Pays-Bas', pt: 'Países Baixos' } },
  { iso3: 'NZL', iso2: 'NZ', name: { en: 'New Zealand', it: 'Nuova Zelanda', es: 'Nueva Zelanda', fr: 'Nouvelle-Zélande', pt: 'Nova Zelândia' } },
  { iso3: 'NIC', iso2: 'NI', name: { en: 'Nicaragua', it: 'Nicaragua', es: 'Nicaragua', fr: 'Nicaragua', pt: 'Nicarágua' } },
  { iso3: 'NER', iso2: 'NE', name: { en: 'Niger', it: 'Niger', es: 'Níger', fr: 'Niger', pt: 'Níger' } },
  { iso3: 'NGA', iso2: 'NG', name: { en: 'Nigeria', it: 'Nigeria', es: 'Nigeria', fr: 'Nigeria', pt: 'Nigéria' } },
  { iso3: 'MKD', iso2: 'MK', name: { en: 'North Macedonia', it: 'Macedonia del Nord', es: 'Macedonia del Norte', fr: 'Macédoine du Nord', pt: 'Macedônia do Norte' } },
  { iso3: 'NOR', iso2: 'NO', name: { en: 'Norway', it: 'Norvegia', es: 'Noruega', fr: 'Norvège', pt: 'Noruega' } },
  { iso3: 'OMN', iso2: 'OM', name: { en: 'Oman', it: 'Oman', es: 'Omán', fr: 'Oman', pt: 'Omã' } },
  { iso3: 'PAK', iso2: 'PK', name: { en: 'Pakistan', it: 'Pakistan', es: 'Pakistán', fr: 'Pakistan', pt: 'Paquistão' } },
  { iso3: 'PLW', iso2: 'PW', name: { en: 'Palau', it: 'Palau', es: 'Palaos', fr: 'Palaos', pt: 'Palau' } },
  { iso3: 'PSE', iso2: 'PS', name: { en: 'Palestine', it: 'Palestina', es: 'Palestina', fr: 'Palestine', pt: 'Palestina' } },
  { iso3: 'PAN', iso2: 'PA', name: { en: 'Panama', it: 'Panama', es: 'Panamá', fr: 'Panama', pt: 'Panamá' } },
  { iso3: 'PNG', iso2: 'PG', name: { en: 'Papua New Guinea', it: 'Papua Nuova Guinea', es: 'Papua Nueva Guinea', fr: 'Papouasie-Nouvelle-Guinée', pt: 'Papua-Nova Guiné' } },
  { iso3: 'PRY', iso2: 'PY', name: { en: 'Paraguay', it: 'Paraguay', es: 'Paraguay', fr: 'Paraguay', pt: 'Paraguai' } },
  { iso3: 'PER', iso2: 'PE', name: { en: 'Peru', it: 'Perù', es: 'Perú', fr: 'Pérou', pt: 'Peru' } },
  { iso3: 'PHL', iso2: 'PH', name: { en: 'Philippines', it: 'Filippine', es: 'Filipinas', fr: 'Philippines', pt: 'Filipinas' } },
  { iso3: 'POL', iso2: 'PL', name: { en: 'Poland', it: 'Polonia', es: 'Polonia', fr: 'Pologne', pt: 'Polônia' } },
  { iso3: 'PRT', iso2: 'PT', name: { en: 'Portugal', it: 'Portogallo', es: 'Portugal', fr: 'Portugal', pt: 'Portugal' } },
  { iso3: 'QAT', iso2: 'QA', name: { en: 'Qatar', it: 'Qatar', es: 'Catar', fr: 'Qatar', pt: 'Catar' } },
  { iso3: 'ROU', iso2: 'RO', name: { en: 'Romania', it: 'Romania', es: 'Rumanía', fr: 'Roumanie', pt: 'Romênia' } },
  { iso3: 'RUS', iso2: 'RU', name: { en: 'Russia', it: 'Russia', es: 'Rusia', fr: 'Russie', pt: 'Rússia' } },
  { iso3: 'RWA', iso2: 'RW', name: { en: 'Rwanda', it: 'Ruanda', es: 'Ruanda', fr: 'Rwanda', pt: 'Ruanda' } },
  { iso3: 'KNA', iso2: 'KN', name: { en: 'Saint Kitts and Nevis', it: 'Saint Kitts e Nevis', es: 'San Cristóbal y Nieves', fr: 'Saint-Kitts-et-Nevis', pt: 'São Cristóvão e Nevis' } },
  { iso3: 'LCA', iso2: 'LC', name: { en: 'Saint Lucia', it: 'Santa Lucia', es: 'Santa Lucía', fr: 'Sainte-Lucie', pt: 'Santa Lúcia' } },
  { iso3: 'VCT', iso2: 'VC', name: { en: 'Saint Vincent and the Grenadines', it: 'Saint Vincent e Grenadine', es: 'San Vicente y las Granadinas', fr: 'Saint-Vincent-et-les-Grenadines', pt: 'São Vicente e Granadinas' } },
  { iso3: 'WSM', iso2: 'WS', name: { en: 'Samoa', it: 'Samoa', es: 'Samoa', fr: 'Samoa', pt: 'Samoa' } },
  { iso3: 'SMR', iso2: 'SM', name: { en: 'San Marino', it: 'San Marino', es: 'San Marino', fr: 'Saint-Marin', pt: 'San Marino' } },
  { iso3: 'STP', iso2: 'ST', name: { en: 'Sao Tome and Principe', it: 'São Tomé e Príncipe', es: 'Santo Tomé y Príncipe', fr: 'Sao Tomé-et-Principe', pt: 'São Tomé e Príncipe' } },
  { iso3: 'SAU', iso2: 'SA', name: { en: 'Saudi Arabia', it: 'Arabia Saudita', es: 'Arabia Saudita', fr: 'Arabie saoudite', pt: 'Arábia Saudita' } },
  { iso3: 'SEN', iso2: 'SN', name: { en: 'Senegal', it: 'Senegal', es: 'Senegal', fr: 'Sénégal', pt: 'Senegal' } },
  { iso3: 'SRB', iso2: 'RS', name: { en: 'Serbia', it: 'Serbia', es: 'Serbia', fr: 'Serbie', pt: 'Sérvia' } },
  { iso3: 'SYC', iso2: 'SC', name: { en: 'Seychelles', it: 'Seychelles', es: 'Seychelles', fr: 'Seychelles', pt: 'Seicheles' } },
  { iso3: 'SLE', iso2: 'SL', name: { en: 'Sierra Leone', it: 'Sierra Leone', es: 'Sierra Leona', fr: 'Sierra Leone', pt: 'Serra Leoa' } },
  { iso3: 'SGP', iso2: 'SG', name: { en: 'Singapore', it: 'Singapore', es: 'Singapur', fr: 'Singapour', pt: 'Singapura' } },
  { iso3: 'SVK', iso2: 'SK', name: { en: 'Slovakia', it: 'Slovacchia', es: 'Eslovaquia', fr: 'Slovaquie', pt: 'Eslováquia' } },
  { iso3: 'SVN', iso2: 'SI', name: { en: 'Slovenia', it: 'Slovenia', es: 'Eslovenia', fr: 'Slovénie', pt: 'Eslovênia' } },
  { iso3: 'SLB', iso2: 'SB', name: { en: 'Solomon Islands', it: 'Isole Salomone', es: 'Islas Salomón', fr: 'Îles Salomon', pt: 'Ilhas Salomão' } },
  { iso3: 'SOM', iso2: 'SO', name: { en: 'Somalia', it: 'Somalia', es: 'Somalia', fr: 'Somalie', pt: 'Somália' } },
  { iso3: 'ZAF', iso2: 'ZA', name: { en: 'South Africa', it: 'Sudafrica', es: 'Sudáfrica', fr: 'Afrique du Sud', pt: 'África do Sul' } },
  { iso3: 'SSD', iso2: 'SS', name: { en: 'South Sudan', it: 'Sudan del Sud', es: 'Sudán del Sur', fr: 'Soudan du Sud', pt: 'Sudão do Sul' } },
  { iso3: 'ESP', iso2: 'ES', name: { en: 'Spain', it: 'Spagna', es: 'España', fr: 'Espagne', pt: 'Espanha' } },
  { iso3: 'LKA', iso2: 'LK', name: { en: 'Sri Lanka', it: 'Sri Lanka', es: 'Sri Lanka', fr: 'Sri Lanka', pt: 'Sri Lanka' } },
  { iso3: 'SDN', iso2: 'SD', name: { en: 'Sudan', it: 'Sudan', es: 'Sudán', fr: 'Soudan', pt: 'Sudão' } },
  { iso3: 'SUR', iso2: 'SR', name: { en: 'Suriname', it: 'Suriname', es: 'Surinam', fr: 'Suriname', pt: 'Suriname' } },
  { iso3: 'SWE', iso2: 'SE', name: { en: 'Sweden', it: 'Svezia', es: 'Suecia', fr: 'Suède', pt: 'Suécia' } },
  { iso3: 'CHE', iso2: 'CH', name: { en: 'Switzerland', it: 'Svizzera', es: 'Suiza', fr: 'Suisse', pt: 'Suíça' } },
  { iso3: 'SYR', iso2: 'SY', name: { en: 'Syria', it: 'Siria', es: 'Siria', fr: 'Syrie', pt: 'Síria' } },
  { iso3: 'TWN', iso2: 'TW', name: { en: 'Taiwan', it: 'Taiwan', es: 'Taiwán', fr: 'Taiwan', pt: 'Taiwan' } },
  { iso3: 'TJK', iso2: 'TJ', name: { en: 'Tajikistan', it: 'Tagikistan', es: 'Tayikistán', fr: 'Tadjikistan', pt: 'Tajiquistão' } },
  { iso3: 'TZA', iso2: 'TZ', name: { en: 'Tanzania', it: 'Tanzania', es: 'Tanzania', fr: 'Tanzanie', pt: 'Tanzânia' } },
  { iso3: 'THA', iso2: 'TH', name: { en: 'Thailand', it: 'Thailandia', es: 'Tailandia', fr: 'Thaïlande', pt: 'Tailândia' } },
  { iso3: 'TLS', iso2: 'TL', name: { en: 'Timor-Leste', it: 'Timor Est', es: 'Timor Oriental', fr: 'Timor oriental', pt: 'Timor-Leste' } },
  { iso3: 'TGO', iso2: 'TG', name: { en: 'Togo', it: 'Togo', es: 'Togo', fr: 'Togo', pt: 'Togo' } },
  { iso3: 'TON', iso2: 'TO', name: { en: 'Tonga', it: 'Tonga', es: 'Tonga', fr: 'Tonga', pt: 'Tonga' } },
  { iso3: 'TTO', iso2: 'TT', name: { en: 'Trinidad and Tobago', it: 'Trinidad e Tobago', es: 'Trinidad y Tobago', fr: 'Trinité-et-Tobago', pt: 'Trinidad e Tobago' } },
  { iso3: 'TUN', iso2: 'TN', name: { en: 'Tunisia', it: 'Tunisia', es: 'Túnez', fr: 'Tunisie', pt: 'Tunísia' } },
  { iso3: 'TUR', iso2: 'TR', name: { en: 'Turkey', it: 'Turchia', es: 'Turquía', fr: 'Turquie', pt: 'Turquia' } },
  { iso3: 'TKM', iso2: 'TM', name: { en: 'Turkmenistan', it: 'Turkmenistan', es: 'Turkmenistán', fr: 'Turkmenistan', pt: 'Turcomenistão' } },
  { iso3: 'TUV', iso2: 'TV', name: { en: 'Tuvalu', it: 'Tuvalu', es: 'Tuvalu', fr: 'Tuvalu', pt: 'Tuvalu' } },
  { iso3: 'UGA', iso2: 'UG', name: { en: 'Uganda', it: 'Uganda', es: 'Uganda', fr: 'Ouganda', pt: 'Uganda' } },
  { iso3: 'UKR', iso2: 'UA', name: { en: 'Ukraine', it: 'Ucraina', es: 'Ucrania', fr: 'Ukraine', pt: 'Ucrânia' } },
  { iso3: 'ARE', iso2: 'AE', name: { en: 'United Arab Emirates', it: 'Emirati Arabi Uniti', es: 'Emiratos Árabes Unidos', fr: 'Émirats arabes unis', pt: 'Emirados Árabes Unidos' } },
  { iso3: 'GBR', iso2: 'GB', name: { en: 'United Kingdom', it: 'Regno Unito', es: 'Reino Unido', fr: 'Royaume-Uni', pt: 'Reino Unido' } },
  { iso3: 'USA', iso2: 'US', name: { en: 'United States', it: 'Stati Uniti', es: 'Estados Unidos', fr: 'États-Unis', pt: 'Estados Unidos' } },
  { iso3: 'URY', iso2: 'UY', name: { en: 'Uruguay', it: 'Uruguay', es: 'Uruguay', fr: 'Uruguay', pt: 'Uruguai' } },
  { iso3: 'UZB', iso2: 'UZ', name: { en: 'Uzbekistan', it: 'Uzbekistan', es: 'Uzbekistán', fr: 'Ouzbékistan', pt: 'Uzbequistão' } },
  { iso3: 'VUT', iso2: 'VU', name: { en: 'Vanuatu', it: 'Vanuatu', es: 'Vanuatu', fr: 'Vanuatu', pt: 'Vanuatu' } },
  { iso3: 'VAT', iso2: 'VA', name: { en: 'Vatican City', it: 'Città del Vaticano', es: 'Ciudad del Vaticano', fr: 'Cité du Vatican', pt: 'Cidade do Vaticano' } },
  { iso3: 'VEN', iso2: 'VE', name: { en: 'Venezuela', it: 'Venezuela', es: 'Venezuela', fr: 'Venezuela', pt: 'Venezuela' } },
  { iso3: 'VNM', iso2: 'VN', name: { en: 'Vietnam', it: 'Vietnam', es: 'Vietnam', fr: 'Viet Nam', pt: 'Vietnã' } },
  { iso3: 'YEM', iso2: 'YE', name: { en: 'Yemen', it: 'Yemen', es: 'Yemen', fr: 'Yémen', pt: 'Iêmen' } },
  { iso3: 'ZMB', iso2: 'ZM', name: { en: 'Zambia', it: 'Zambia', es: 'Zambia', fr: 'Zambie', pt: 'Zâmbia' } },
  { iso3: 'ZWE', iso2: 'ZW', name: { en: 'Zimbabwe', it: 'Zimbabwe', es: 'Zimbabue', fr: 'Zimbabwe', pt: 'Zimbabue' } },
  // Additional territories and smaller states
  { iso3: 'ABW', iso2: 'AW', name: { en: 'Aruba', it: 'Aruba', es: 'Aruba', fr: 'Aruba', pt: 'Aruba' } },
  { iso3: 'ALA', iso2: 'AX', name: { en: 'Aland Islands', it: 'Isole Åland', es: 'Islas Aland', fr: 'Îles Åland', pt: 'Ilhas Aland' } },
  { iso3: 'ASM', iso2: 'AS', name: { en: 'American Samoa', it: 'Samoa Americane', es: 'Samoa Americana', fr: 'Samoa américaines', pt: 'Samoa Americana' } },
  { iso3: 'AIA', iso2: 'AI', name: { en: 'Anguilla', it: 'Anguilla', es: 'Anguila', fr: 'Anguilla', pt: 'Anguila' } },
  { iso3: 'ATA', iso2: 'AQ', name: { en: 'Antarctica', it: 'Antartide', es: 'Antártida', fr: 'Antarctique', pt: 'Antártida' } },
  { iso3: 'BES', iso2: 'BQ', name: { en: 'Bonaire, Sint Eustatius and Saba', it: 'Bonaire, Sint Eustatius e Saba', es: 'Bonaire, San Eustaquio y Saba', fr: 'Bonaire, Saint-Eustache et Saba', pt: 'Bonaire, Santo Eustáquio e Saba' } },
  { iso3: 'BVT', iso2: 'BV', name: { en: 'Bouvet Island', it: 'Isola Bouvet', es: 'Isla Bouvet', fr: 'Île Bouvet', pt: 'Ilha Bouvet' } },
  { iso3: 'IOT', iso2: 'IO', name: { en: 'British Indian Ocean Territory', it: 'Territorio Britannico dell\'Oceano Indiano', es: 'Territorio Británico del Océano Índico', fr: 'Territoire britannique de l\'océan Indien', pt: 'Território Britânico do Oceano Índico' } },
  { iso3: 'CYM', iso2: 'KY', name: { en: 'Cayman Islands', it: 'Isole Cayman', es: 'Islas Caimán', fr: 'Îles Caïmans', pt: 'Ilhas Cayman' } },
  { iso3: 'CXR', iso2: 'CX', name: { en: 'Christmas Island', it: 'Isola di Natale', es: 'Isla de Navidad', fr: 'Île Christmas', pt: 'Ilha Christmas' } },
  { iso3: 'CCK', iso2: 'CC', name: { en: 'Cocos (Keeling) Islands', it: 'Isole Cocos', es: 'Islas Cocos', fr: 'Îles Cocos', pt: 'Ilhas Cocos' } },
  { iso3: 'COK', iso2: 'CK', name: { en: 'Cook Islands', it: 'Isole Cook', es: 'Islas Cook', fr: 'Îles Cook', pt: 'Ilhas Cook' } },
  { iso3: 'CUW', iso2: 'CW', name: { en: 'Curacao', it: 'Curaçao', es: 'Curazao', fr: 'Curaçao', pt: 'Curaçao' } },
  { iso3: 'FLK', iso2: 'FK', name: { en: 'Falkland Islands', it: 'Isole Falkland', es: 'Islas Malvinas', fr: 'Îles Malouines', pt: 'Ilhas Malvinas' } },
  { iso3: 'FRO', iso2: 'FO', name: { en: 'Faroe Islands', it: 'Isole Faroe', es: 'Islas Feroe', fr: 'Îles Féroé', pt: 'Ilhas Faroe' } },
  { iso3: 'GUF', iso2: 'GF', name: { en: 'French Guiana', it: 'Guyana Francese', es: 'Guayana Francesa', fr: 'Guyane française', pt: 'Guiana Francesa' } },
  { iso3: 'PYF', iso2: 'PF', name: { en: 'French Polynesia', it: 'Polinesia Francese', es: 'Polinesia Francesa', fr: 'Polynésie française', pt: 'Polinésia Francesa' } },
  { iso3: 'ATF', iso2: 'TF', name: { en: 'French Southern Territories', it: 'Terre Australi Francesi', es: 'Tierras Australes Francesas', fr: 'Terres australes françaises', pt: 'Terras Austrais Francesas' } },
  { iso3: 'GIB', iso2: 'GI', name: { en: 'Gibraltar', it: 'Gibilterra', es: 'Gibraltar', fr: 'Gibraltar', pt: 'Gibraltar' } },
  { iso3: 'GRL', iso2: 'GL', name: { en: 'Greenland', it: 'Groenlandia', es: 'Groenlandia', fr: 'Groenland', pt: 'Groenlândia' } },
  { iso3: 'GLP', iso2: 'GP', name: { en: 'Guadeloupe', it: 'Guadalupa', es: 'Guadalupe', fr: 'Guadeloupe', pt: 'Guadalupe' } },
  { iso3: 'GUM', iso2: 'GU', name: { en: 'Guam', it: 'Guam', es: 'Guam', fr: 'Guam', pt: 'Guam' } },
  { iso3: 'HKG', iso2: 'HK', name: { en: 'Hong Kong', it: 'Hong Kong', es: 'Hong Kong', fr: 'Hong Kong', pt: 'Hong Kong' } },
  { iso3: 'IMN', iso2: 'IM', name: { en: 'Isle of Man', it: 'Isola di Man', es: 'Isla de Man', fr: 'Île de Man', pt: 'Ilha de Man' } },
  { iso3: 'JEY', iso2: 'JE', name: { en: 'Jersey', it: 'Jersey', es: 'Jersey', fr: 'Jersey', pt: 'Jersey' } },
  { iso3: 'GGY', iso2: 'GG', name: { en: 'Guernsey', it: 'Guernsey', es: 'Guernsey', fr: 'Guernesey', pt: 'Guernsey' } },
  { iso3: 'XKX', iso2: 'XK', name: { en: 'Kosovo', it: 'Kosovo', es: 'Kosovo', fr: 'Kosovo', pt: 'Kosovo' } },
  { iso3: 'MAC', iso2: 'MO', name: { en: 'Macao', it: 'Macao', es: 'Macao', fr: 'Macao', pt: 'Macau' } },
  { iso3: 'MTQ', iso2: 'MQ', name: { en: 'Martinique', it: 'Martinica', es: 'Martinica', fr: 'Martinique', pt: 'Martinica' } },
  { iso3: 'MYT', iso2: 'YT', name: { en: 'Mayotte', it: 'Mayotte', es: 'Mayotte', fr: 'Mayotte', pt: 'Mayotte' } },
  { iso3: 'MSR', iso2: 'MS', name: { en: 'Montserrat', it: 'Montserrat', es: 'Montserrat', fr: 'Montserrat', pt: 'Montserrat' } },
  { iso3: 'NCL', iso2: 'NC', name: { en: 'New Caledonia', it: 'Nuova Caledonia', es: 'Nueva Caledonia', fr: 'Nouvelle-Calédonie', pt: 'Nova Caledônia' } },
  { iso3: 'NIU', iso2: 'NU', name: { en: 'Niue', it: 'Niue', es: 'Niue', fr: 'Niue', pt: 'Niue' } },
  { iso3: 'NFK', iso2: 'NF', name: { en: 'Norfolk Island', it: 'Isola Norfolk', es: 'Isla Norfolk', fr: 'Île Norfolk', pt: 'Ilha Norfolk' } },
  { iso3: 'MNP', iso2: 'MP', name: { en: 'Northern Mariana Islands', it: 'Isole Marianne Settentrionali', es: 'Islas Marianas del Norte', fr: 'Îles Mariannes du Nord', pt: 'Ilhas Marianas do Norte' } },
  { iso3: 'PCN', iso2: 'PN', name: { en: 'Pitcairn', it: 'Pitcairn', es: 'Pitcairn', fr: 'Pitcairn', pt: 'Pitcairn' } },
  { iso3: 'PRI', iso2: 'PR', name: { en: 'Puerto Rico', it: 'Porto Rico', es: 'Puerto Rico', fr: 'Porto Rico', pt: 'Porto Rico' } },
  { iso3: 'REU', iso2: 'RE', name: { en: 'Reunion', it: 'Riunione', es: 'Reunión', fr: 'La Réunion', pt: 'Reunião' } },
  { iso3: 'BLM', iso2: 'BL', name: { en: 'Saint Barthelemy', it: 'Saint-Barthélemy', es: 'San Bartolomé', fr: 'Saint-Barthélemy', pt: 'São Bartolomeu' } },
  { iso3: 'SHN', iso2: 'SH', name: { en: 'Saint Helena', it: 'Sant\'Elena', es: 'Santa Elena', fr: 'Sainte-Hélène', pt: 'Santa Helena' } },
  { iso3: 'MAF', iso2: 'MF', name: { en: 'Saint Martin', it: 'Saint Martin', es: 'San Martín', fr: 'Saint-Martin', pt: 'São Martinho' } },
  { iso3: 'SPM', iso2: 'PM', name: { en: 'Saint Pierre and Miquelon', it: 'Saint-Pierre e Miquelon', es: 'San Pedro y Miquelón', fr: 'Saint-Pierre-et-Miquelon', pt: 'São Pedro e Miquelon' } },
  { iso3: 'SXM', iso2: 'SX', name: { en: 'Sint Maarten', it: 'Sint Maarten', es: 'Sint Maarten', fr: 'Sint Maarten', pt: 'Sint Maarten' } },
  { iso3: 'SGS', iso2: 'GS', name: { en: 'South Georgia', it: 'Georgia del Sud', es: 'Georgia del Sur', fr: 'Géorgie du Sud', pt: 'Geórgia do Sul' } },
  { iso3: 'SJM', iso2: 'SJ', name: { en: 'Svalbard and Jan Mayen', it: 'Svalbard e Jan Mayen', es: 'Svalbard y Jan Mayen', fr: 'Svalbard et Jan Mayen', pt: 'Svalbard e Jan Mayen' } },
  { iso3: 'TKL', iso2: 'TK', name: { en: 'Tokelau', it: 'Tokelau', es: 'Tokelau', fr: 'Tokelau', pt: 'Tokelau' } },
  { iso3: 'TCA', iso2: 'TC', name: { en: 'Turks and Caicos Islands', it: 'Isole Turks e Caicos', es: 'Islas Turcas y Caicos', fr: 'Îles Turques-et-Caïques', pt: 'Ilhas Turks e Caicos' } },
  { iso3: 'UMI', iso2: 'UM', name: { en: 'US Minor Outlying Islands', it: 'Isole Minori degli Stati Uniti', es: 'Islas Menores de Estados Unidos', fr: 'Îles mineures éloignées des États-Unis', pt: 'Ilhas Menores Distantes dos Estados Unidos' } },
  { iso3: 'VIR', iso2: 'VI', name: { en: 'US Virgin Islands', it: 'Isole Vergini Americane', es: 'Islas Vírgenes de EE.UU.', fr: 'Îles Vierges américaines', pt: 'Ilhas Virgens Americanas' } },
  { iso3: 'VGB', iso2: 'VG', name: { en: 'British Virgin Islands', it: 'Isole Vergini Britanniche', es: 'Islas Vírgenes Británicas', fr: 'Îles Vierges britanniques', pt: 'Ilhas Virgens Britânicas' } },
  { iso3: 'WLF', iso2: 'WF', name: { en: 'Wallis and Futuna', it: 'Wallis e Futuna', es: 'Wallis y Futuna', fr: 'Wallis-et-Futuna', pt: 'Wallis e Futuna' } },
  { iso3: 'ESH', iso2: 'EH', name: { en: 'Western Sahara', it: 'Sahara Occidentale', es: 'Sahara Occidental', fr: 'Sahara occidental', pt: 'Saara Ocidental' } },
];

// Lookup maps for fast access
const iso3Map = new Map<string, CountryEntry>();
const iso2Map = new Map<string, CountryEntry>();
const nameMap = new Map<string, CountryEntry>();

for (const country of COUNTRIES) {
  iso3Map.set(country.iso3, country);
  iso2Map.set(country.iso2, country);
  nameMap.set(country.name.en.toLowerCase(), country);
}

export function getCountryByIso3(iso3: string): CountryEntry | undefined {
  return iso3Map.get(iso3.toUpperCase());
}

export function getCountryByIso2(iso2: string): CountryEntry | undefined {
  return iso2Map.get(iso2.toUpperCase());
}

export function getCountryByName(name: string): CountryEntry | undefined {
  return nameMap.get(name.toLowerCase());
}

export function getCountryName(iso3: string, lang: 'en' | 'it' | 'es' | 'fr' | 'pt' | 'zh' | 'de' = 'en'): string {
  const entry = iso3Map.get(iso3.toUpperCase());
  // Pipeline data only has en/it/es/fr/pt; zh/de fall back to en safely.
  return entry?.name[lang as 'en'] ?? entry?.name.en ?? iso3;
}
