import type { CountryEntry } from '../types.js';

export const COUNTRIES: CountryEntry[] = [
  { iso3: 'AFG', iso2: 'AF', name: { en: 'Afghanistan', it: 'Afghanistan', es: 'Afganistan' } },
  { iso3: 'ALB', iso2: 'AL', name: { en: 'Albania', it: 'Albania', es: 'Albania' } },
  { iso3: 'DZA', iso2: 'DZ', name: { en: 'Algeria', it: 'Algeria', es: 'Argelia' } },
  { iso3: 'AND', iso2: 'AD', name: { en: 'Andorra', it: 'Andorra', es: 'Andorra' } },
  { iso3: 'AGO', iso2: 'AO', name: { en: 'Angola', it: 'Angola', es: 'Angola' } },
  { iso3: 'ATG', iso2: 'AG', name: { en: 'Antigua and Barbuda', it: 'Antigua e Barbuda', es: 'Antigua y Barbuda' } },
  { iso3: 'ARG', iso2: 'AR', name: { en: 'Argentina', it: 'Argentina', es: 'Argentina' } },
  { iso3: 'ARM', iso2: 'AM', name: { en: 'Armenia', it: 'Armenia', es: 'Armenia' } },
  { iso3: 'AUS', iso2: 'AU', name: { en: 'Australia', it: 'Australia', es: 'Australia' } },
  { iso3: 'AUT', iso2: 'AT', name: { en: 'Austria', it: 'Austria', es: 'Austria' } },
  { iso3: 'AZE', iso2: 'AZ', name: { en: 'Azerbaijan', it: 'Azerbaigian', es: 'Azerbaiyan' } },
  { iso3: 'BHS', iso2: 'BS', name: { en: 'Bahamas', it: 'Bahamas', es: 'Bahamas' } },
  { iso3: 'BHR', iso2: 'BH', name: { en: 'Bahrain', it: 'Bahrein', es: 'Barein' } },
  { iso3: 'BGD', iso2: 'BD', name: { en: 'Bangladesh', it: 'Bangladesh', es: 'Bangladesh' } },
  { iso3: 'BRB', iso2: 'BB', name: { en: 'Barbados', it: 'Barbados', es: 'Barbados' } },
  { iso3: 'BLR', iso2: 'BY', name: { en: 'Belarus', it: 'Bielorussia', es: 'Bielorrusia' } },
  { iso3: 'BEL', iso2: 'BE', name: { en: 'Belgium', it: 'Belgio', es: 'Belgica' } },
  { iso3: 'BLZ', iso2: 'BZ', name: { en: 'Belize', it: 'Belize', es: 'Belice' } },
  { iso3: 'BEN', iso2: 'BJ', name: { en: 'Benin', it: 'Benin', es: 'Benin' } },
  { iso3: 'BTN', iso2: 'BT', name: { en: 'Bhutan', it: 'Bhutan', es: 'Butan' } },
  { iso3: 'BOL', iso2: 'BO', name: { en: 'Bolivia', it: 'Bolivia', es: 'Bolivia' } },
  { iso3: 'BIH', iso2: 'BA', name: { en: 'Bosnia and Herzegovina', it: 'Bosnia ed Erzegovina', es: 'Bosnia y Herzegovina' } },
  { iso3: 'BWA', iso2: 'BW', name: { en: 'Botswana', it: 'Botswana', es: 'Botsuana' } },
  { iso3: 'BRA', iso2: 'BR', name: { en: 'Brazil', it: 'Brasile', es: 'Brasil' } },
  { iso3: 'BRN', iso2: 'BN', name: { en: 'Brunei', it: 'Brunei', es: 'Brunei' } },
  { iso3: 'BGR', iso2: 'BG', name: { en: 'Bulgaria', it: 'Bulgaria', es: 'Bulgaria' } },
  { iso3: 'BFA', iso2: 'BF', name: { en: 'Burkina Faso', it: 'Burkina Faso', es: 'Burkina Faso' } },
  { iso3: 'BDI', iso2: 'BI', name: { en: 'Burundi', it: 'Burundi', es: 'Burundi' } },
  { iso3: 'CPV', iso2: 'CV', name: { en: 'Cabo Verde', it: 'Capo Verde', es: 'Cabo Verde' } },
  { iso3: 'KHM', iso2: 'KH', name: { en: 'Cambodia', it: 'Cambogia', es: 'Camboya' } },
  { iso3: 'CMR', iso2: 'CM', name: { en: 'Cameroon', it: 'Camerun', es: 'Camerun' } },
  { iso3: 'CAN', iso2: 'CA', name: { en: 'Canada', it: 'Canada', es: 'Canada' } },
  { iso3: 'CAF', iso2: 'CF', name: { en: 'Central African Republic', it: 'Repubblica Centrafricana', es: 'Republica Centroafricana' } },
  { iso3: 'TCD', iso2: 'TD', name: { en: 'Chad', it: 'Ciad', es: 'Chad' } },
  { iso3: 'CHL', iso2: 'CL', name: { en: 'Chile', it: 'Cile', es: 'Chile' } },
  { iso3: 'CHN', iso2: 'CN', name: { en: 'China', it: 'Cina', es: 'China' } },
  { iso3: 'COL', iso2: 'CO', name: { en: 'Colombia', it: 'Colombia', es: 'Colombia' } },
  { iso3: 'COM', iso2: 'KM', name: { en: 'Comoros', it: 'Comore', es: 'Comoras' } },
  { iso3: 'COG', iso2: 'CG', name: { en: 'Congo', it: 'Congo', es: 'Congo' } },
  { iso3: 'COD', iso2: 'CD', name: { en: 'Democratic Republic of the Congo', it: 'Repubblica Democratica del Congo', es: 'Republica Democratica del Congo' } },
  { iso3: 'CRI', iso2: 'CR', name: { en: 'Costa Rica', it: 'Costa Rica', es: 'Costa Rica' } },
  { iso3: 'CIV', iso2: 'CI', name: { en: "Cote d'Ivoire", it: "Costa d'Avorio", es: "Costa de Marfil" } },
  { iso3: 'HRV', iso2: 'HR', name: { en: 'Croatia', it: 'Croazia', es: 'Croacia' } },
  { iso3: 'CUB', iso2: 'CU', name: { en: 'Cuba', it: 'Cuba', es: 'Cuba' } },
  { iso3: 'CYP', iso2: 'CY', name: { en: 'Cyprus', it: 'Cipro', es: 'Chipre' } },
  { iso3: 'CZE', iso2: 'CZ', name: { en: 'Czech Republic', it: 'Repubblica Ceca', es: 'Republica Checa' } },
  { iso3: 'DNK', iso2: 'DK', name: { en: 'Denmark', it: 'Danimarca', es: 'Dinamarca' } },
  { iso3: 'DJI', iso2: 'DJ', name: { en: 'Djibouti', it: 'Gibuti', es: 'Yibuti' } },
  { iso3: 'DMA', iso2: 'DM', name: { en: 'Dominica', it: 'Dominica', es: 'Dominica' } },
  { iso3: 'DOM', iso2: 'DO', name: { en: 'Dominican Republic', it: 'Repubblica Dominicana', es: 'Republica Dominicana' } },
  { iso3: 'ECU', iso2: 'EC', name: { en: 'Ecuador', it: 'Ecuador', es: 'Ecuador' } },
  { iso3: 'EGY', iso2: 'EG', name: { en: 'Egypt', it: 'Egitto', es: 'Egipto' } },
  { iso3: 'SLV', iso2: 'SV', name: { en: 'El Salvador', it: 'El Salvador', es: 'El Salvador' } },
  { iso3: 'GNQ', iso2: 'GQ', name: { en: 'Equatorial Guinea', it: 'Guinea Equatoriale', es: 'Guinea Ecuatorial' } },
  { iso3: 'ERI', iso2: 'ER', name: { en: 'Eritrea', it: 'Eritrea', es: 'Eritrea' } },
  { iso3: 'EST', iso2: 'EE', name: { en: 'Estonia', it: 'Estonia', es: 'Estonia' } },
  { iso3: 'SWZ', iso2: 'SZ', name: { en: 'Eswatini', it: 'Eswatini', es: 'Esuatini' } },
  { iso3: 'ETH', iso2: 'ET', name: { en: 'Ethiopia', it: 'Etiopia', es: 'Etiopia' } },
  { iso3: 'FJI', iso2: 'FJ', name: { en: 'Fiji', it: 'Figi', es: 'Fiyi' } },
  { iso3: 'FIN', iso2: 'FI', name: { en: 'Finland', it: 'Finlandia', es: 'Finlandia' } },
  { iso3: 'FRA', iso2: 'FR', name: { en: 'France', it: 'Francia', es: 'Francia' } },
  { iso3: 'GAB', iso2: 'GA', name: { en: 'Gabon', it: 'Gabon', es: 'Gabon' } },
  { iso3: 'GMB', iso2: 'GM', name: { en: 'Gambia', it: 'Gambia', es: 'Gambia' } },
  { iso3: 'GEO', iso2: 'GE', name: { en: 'Georgia', it: 'Georgia', es: 'Georgia' } },
  { iso3: 'DEU', iso2: 'DE', name: { en: 'Germany', it: 'Germania', es: 'Alemania' } },
  { iso3: 'GHA', iso2: 'GH', name: { en: 'Ghana', it: 'Ghana', es: 'Ghana' } },
  { iso3: 'GRC', iso2: 'GR', name: { en: 'Greece', it: 'Grecia', es: 'Grecia' } },
  { iso3: 'GRD', iso2: 'GD', name: { en: 'Grenada', it: 'Grenada', es: 'Granada' } },
  { iso3: 'GTM', iso2: 'GT', name: { en: 'Guatemala', it: 'Guatemala', es: 'Guatemala' } },
  { iso3: 'GIN', iso2: 'GN', name: { en: 'Guinea', it: 'Guinea', es: 'Guinea' } },
  { iso3: 'GNB', iso2: 'GW', name: { en: 'Guinea-Bissau', it: 'Guinea-Bissau', es: 'Guinea-Bisau' } },
  { iso3: 'GUY', iso2: 'GY', name: { en: 'Guyana', it: 'Guyana', es: 'Guyana' } },
  { iso3: 'HTI', iso2: 'HT', name: { en: 'Haiti', it: 'Haiti', es: 'Haiti' } },
  { iso3: 'HND', iso2: 'HN', name: { en: 'Honduras', it: 'Honduras', es: 'Honduras' } },
  { iso3: 'HUN', iso2: 'HU', name: { en: 'Hungary', it: 'Ungheria', es: 'Hungria' } },
  { iso3: 'ISL', iso2: 'IS', name: { en: 'Iceland', it: 'Islanda', es: 'Islandia' } },
  { iso3: 'IND', iso2: 'IN', name: { en: 'India', it: 'India', es: 'India' } },
  { iso3: 'IDN', iso2: 'ID', name: { en: 'Indonesia', it: 'Indonesia', es: 'Indonesia' } },
  { iso3: 'IRN', iso2: 'IR', name: { en: 'Iran', it: 'Iran', es: 'Iran' } },
  { iso3: 'IRQ', iso2: 'IQ', name: { en: 'Iraq', it: 'Iraq', es: 'Irak' } },
  { iso3: 'IRL', iso2: 'IE', name: { en: 'Ireland', it: 'Irlanda', es: 'Irlanda' } },
  { iso3: 'ISR', iso2: 'IL', name: { en: 'Israel', it: 'Israele', es: 'Israel' } },
  { iso3: 'ITA', iso2: 'IT', name: { en: 'Italy', it: 'Italia', es: 'Italia' } },
  { iso3: 'JAM', iso2: 'JM', name: { en: 'Jamaica', it: 'Giamaica', es: 'Jamaica' } },
  { iso3: 'JPN', iso2: 'JP', name: { en: 'Japan', it: 'Giappone', es: 'Japon' } },
  { iso3: 'JOR', iso2: 'JO', name: { en: 'Jordan', it: 'Giordania', es: 'Jordania' } },
  { iso3: 'KAZ', iso2: 'KZ', name: { en: 'Kazakhstan', it: 'Kazakistan', es: 'Kazajistan' } },
  { iso3: 'KEN', iso2: 'KE', name: { en: 'Kenya', it: 'Kenya', es: 'Kenia' } },
  { iso3: 'KIR', iso2: 'KI', name: { en: 'Kiribati', it: 'Kiribati', es: 'Kiribati' } },
  { iso3: 'PRK', iso2: 'KP', name: { en: 'North Korea', it: 'Corea del Nord', es: 'Corea del Norte' } },
  { iso3: 'KOR', iso2: 'KR', name: { en: 'South Korea', it: 'Corea del Sud', es: 'Corea del Sur' } },
  { iso3: 'KWT', iso2: 'KW', name: { en: 'Kuwait', it: 'Kuwait', es: 'Kuwait' } },
  { iso3: 'KGZ', iso2: 'KG', name: { en: 'Kyrgyzstan', it: 'Kirghizistan', es: 'Kirguistan' } },
  { iso3: 'LAO', iso2: 'LA', name: { en: 'Laos', it: 'Laos', es: 'Laos' } },
  { iso3: 'LVA', iso2: 'LV', name: { en: 'Latvia', it: 'Lettonia', es: 'Letonia' } },
  { iso3: 'LBN', iso2: 'LB', name: { en: 'Lebanon', it: 'Libano', es: 'Libano' } },
  { iso3: 'LSO', iso2: 'LS', name: { en: 'Lesotho', it: 'Lesotho', es: 'Lesoto' } },
  { iso3: 'LBR', iso2: 'LR', name: { en: 'Liberia', it: 'Liberia', es: 'Liberia' } },
  { iso3: 'LBY', iso2: 'LY', name: { en: 'Libya', it: 'Libia', es: 'Libia' } },
  { iso3: 'LIE', iso2: 'LI', name: { en: 'Liechtenstein', it: 'Liechtenstein', es: 'Liechtenstein' } },
  { iso3: 'LTU', iso2: 'LT', name: { en: 'Lithuania', it: 'Lituania', es: 'Lituania' } },
  { iso3: 'LUX', iso2: 'LU', name: { en: 'Luxembourg', it: 'Lussemburgo', es: 'Luxemburgo' } },
  { iso3: 'MDG', iso2: 'MG', name: { en: 'Madagascar', it: 'Madagascar', es: 'Madagascar' } },
  { iso3: 'MWI', iso2: 'MW', name: { en: 'Malawi', it: 'Malawi', es: 'Malaui' } },
  { iso3: 'MYS', iso2: 'MY', name: { en: 'Malaysia', it: 'Malesia', es: 'Malasia' } },
  { iso3: 'MDV', iso2: 'MV', name: { en: 'Maldives', it: 'Maldive', es: 'Maldivas' } },
  { iso3: 'MLI', iso2: 'ML', name: { en: 'Mali', it: 'Mali', es: 'Mali' } },
  { iso3: 'MLT', iso2: 'MT', name: { en: 'Malta', it: 'Malta', es: 'Malta' } },
  { iso3: 'MHL', iso2: 'MH', name: { en: 'Marshall Islands', it: 'Isole Marshall', es: 'Islas Marshall' } },
  { iso3: 'MRT', iso2: 'MR', name: { en: 'Mauritania', it: 'Mauritania', es: 'Mauritania' } },
  { iso3: 'MUS', iso2: 'MU', name: { en: 'Mauritius', it: 'Mauritius', es: 'Mauricio' } },
  { iso3: 'MEX', iso2: 'MX', name: { en: 'Mexico', it: 'Messico', es: 'Mexico' } },
  { iso3: 'FSM', iso2: 'FM', name: { en: 'Micronesia', it: 'Micronesia', es: 'Micronesia' } },
  { iso3: 'MDA', iso2: 'MD', name: { en: 'Moldova', it: 'Moldavia', es: 'Moldavia' } },
  { iso3: 'MCO', iso2: 'MC', name: { en: 'Monaco', it: 'Monaco', es: 'Monaco' } },
  { iso3: 'MNG', iso2: 'MN', name: { en: 'Mongolia', it: 'Mongolia', es: 'Mongolia' } },
  { iso3: 'MNE', iso2: 'ME', name: { en: 'Montenegro', it: 'Montenegro', es: 'Montenegro' } },
  { iso3: 'MAR', iso2: 'MA', name: { en: 'Morocco', it: 'Marocco', es: 'Marruecos' } },
  { iso3: 'MOZ', iso2: 'MZ', name: { en: 'Mozambique', it: 'Mozambico', es: 'Mozambique' } },
  { iso3: 'MMR', iso2: 'MM', name: { en: 'Myanmar', it: 'Myanmar', es: 'Myanmar' } },
  { iso3: 'NAM', iso2: 'NA', name: { en: 'Namibia', it: 'Namibia', es: 'Namibia' } },
  { iso3: 'NRU', iso2: 'NR', name: { en: 'Nauru', it: 'Nauru', es: 'Nauru' } },
  { iso3: 'NPL', iso2: 'NP', name: { en: 'Nepal', it: 'Nepal', es: 'Nepal' } },
  { iso3: 'NLD', iso2: 'NL', name: { en: 'Netherlands', it: 'Paesi Bassi', es: 'Paises Bajos' } },
  { iso3: 'NZL', iso2: 'NZ', name: { en: 'New Zealand', it: 'Nuova Zelanda', es: 'Nueva Zelanda' } },
  { iso3: 'NIC', iso2: 'NI', name: { en: 'Nicaragua', it: 'Nicaragua', es: 'Nicaragua' } },
  { iso3: 'NER', iso2: 'NE', name: { en: 'Niger', it: 'Niger', es: 'Niger' } },
  { iso3: 'NGA', iso2: 'NG', name: { en: 'Nigeria', it: 'Nigeria', es: 'Nigeria' } },
  { iso3: 'MKD', iso2: 'MK', name: { en: 'North Macedonia', it: 'Macedonia del Nord', es: 'Macedonia del Norte' } },
  { iso3: 'NOR', iso2: 'NO', name: { en: 'Norway', it: 'Norvegia', es: 'Noruega' } },
  { iso3: 'OMN', iso2: 'OM', name: { en: 'Oman', it: 'Oman', es: 'Oman' } },
  { iso3: 'PAK', iso2: 'PK', name: { en: 'Pakistan', it: 'Pakistan', es: 'Pakistan' } },
  { iso3: 'PLW', iso2: 'PW', name: { en: 'Palau', it: 'Palau', es: 'Palaos' } },
  { iso3: 'PSE', iso2: 'PS', name: { en: 'Palestine', it: 'Palestina', es: 'Palestina' } },
  { iso3: 'PAN', iso2: 'PA', name: { en: 'Panama', it: 'Panama', es: 'Panama' } },
  { iso3: 'PNG', iso2: 'PG', name: { en: 'Papua New Guinea', it: 'Papua Nuova Guinea', es: 'Papua Nueva Guinea' } },
  { iso3: 'PRY', iso2: 'PY', name: { en: 'Paraguay', it: 'Paraguay', es: 'Paraguay' } },
  { iso3: 'PER', iso2: 'PE', name: { en: 'Peru', it: 'Peru', es: 'Peru' } },
  { iso3: 'PHL', iso2: 'PH', name: { en: 'Philippines', it: 'Filippine', es: 'Filipinas' } },
  { iso3: 'POL', iso2: 'PL', name: { en: 'Poland', it: 'Polonia', es: 'Polonia' } },
  { iso3: 'PRT', iso2: 'PT', name: { en: 'Portugal', it: 'Portogallo', es: 'Portugal' } },
  { iso3: 'QAT', iso2: 'QA', name: { en: 'Qatar', it: 'Qatar', es: 'Catar' } },
  { iso3: 'ROU', iso2: 'RO', name: { en: 'Romania', it: 'Romania', es: 'Rumania' } },
  { iso3: 'RUS', iso2: 'RU', name: { en: 'Russia', it: 'Russia', es: 'Rusia' } },
  { iso3: 'RWA', iso2: 'RW', name: { en: 'Rwanda', it: 'Ruanda', es: 'Ruanda' } },
  { iso3: 'KNA', iso2: 'KN', name: { en: 'Saint Kitts and Nevis', it: 'Saint Kitts e Nevis', es: 'San Cristobal y Nieves' } },
  { iso3: 'LCA', iso2: 'LC', name: { en: 'Saint Lucia', it: 'Santa Lucia', es: 'Santa Lucia' } },
  { iso3: 'VCT', iso2: 'VC', name: { en: 'Saint Vincent and the Grenadines', it: 'Saint Vincent e Grenadine', es: 'San Vicente y las Granadinas' } },
  { iso3: 'WSM', iso2: 'WS', name: { en: 'Samoa', it: 'Samoa', es: 'Samoa' } },
  { iso3: 'SMR', iso2: 'SM', name: { en: 'San Marino', it: 'San Marino', es: 'San Marino' } },
  { iso3: 'STP', iso2: 'ST', name: { en: 'Sao Tome and Principe', it: 'Sao Tome e Principe', es: 'Santo Tome y Principe' } },
  { iso3: 'SAU', iso2: 'SA', name: { en: 'Saudi Arabia', it: 'Arabia Saudita', es: 'Arabia Saudita' } },
  { iso3: 'SEN', iso2: 'SN', name: { en: 'Senegal', it: 'Senegal', es: 'Senegal' } },
  { iso3: 'SRB', iso2: 'RS', name: { en: 'Serbia', it: 'Serbia', es: 'Serbia' } },
  { iso3: 'SYC', iso2: 'SC', name: { en: 'Seychelles', it: 'Seychelles', es: 'Seychelles' } },
  { iso3: 'SLE', iso2: 'SL', name: { en: 'Sierra Leone', it: 'Sierra Leone', es: 'Sierra Leona' } },
  { iso3: 'SGP', iso2: 'SG', name: { en: 'Singapore', it: 'Singapore', es: 'Singapur' } },
  { iso3: 'SVK', iso2: 'SK', name: { en: 'Slovakia', it: 'Slovacchia', es: 'Eslovaquia' } },
  { iso3: 'SVN', iso2: 'SI', name: { en: 'Slovenia', it: 'Slovenia', es: 'Eslovenia' } },
  { iso3: 'SLB', iso2: 'SB', name: { en: 'Solomon Islands', it: 'Isole Salomone', es: 'Islas Salomon' } },
  { iso3: 'SOM', iso2: 'SO', name: { en: 'Somalia', it: 'Somalia', es: 'Somalia' } },
  { iso3: 'ZAF', iso2: 'ZA', name: { en: 'South Africa', it: 'Sudafrica', es: 'Sudafrica' } },
  { iso3: 'SSD', iso2: 'SS', name: { en: 'South Sudan', it: 'Sudan del Sud', es: 'Sudan del Sur' } },
  { iso3: 'ESP', iso2: 'ES', name: { en: 'Spain', it: 'Spagna', es: 'Espana' } },
  { iso3: 'LKA', iso2: 'LK', name: { en: 'Sri Lanka', it: 'Sri Lanka', es: 'Sri Lanka' } },
  { iso3: 'SDN', iso2: 'SD', name: { en: 'Sudan', it: 'Sudan', es: 'Sudan' } },
  { iso3: 'SUR', iso2: 'SR', name: { en: 'Suriname', it: 'Suriname', es: 'Surinam' } },
  { iso3: 'SWE', iso2: 'SE', name: { en: 'Sweden', it: 'Svezia', es: 'Suecia' } },
  { iso3: 'CHE', iso2: 'CH', name: { en: 'Switzerland', it: 'Svizzera', es: 'Suiza' } },
  { iso3: 'SYR', iso2: 'SY', name: { en: 'Syria', it: 'Siria', es: 'Siria' } },
  { iso3: 'TWN', iso2: 'TW', name: { en: 'Taiwan', it: 'Taiwan', es: 'Taiwan' } },
  { iso3: 'TJK', iso2: 'TJ', name: { en: 'Tajikistan', it: 'Tagikistan', es: 'Tayikistan' } },
  { iso3: 'TZA', iso2: 'TZ', name: { en: 'Tanzania', it: 'Tanzania', es: 'Tanzania' } },
  { iso3: 'THA', iso2: 'TH', name: { en: 'Thailand', it: 'Thailandia', es: 'Tailandia' } },
  { iso3: 'TLS', iso2: 'TL', name: { en: 'Timor-Leste', it: 'Timor Est', es: 'Timor Oriental' } },
  { iso3: 'TGO', iso2: 'TG', name: { en: 'Togo', it: 'Togo', es: 'Togo' } },
  { iso3: 'TON', iso2: 'TO', name: { en: 'Tonga', it: 'Tonga', es: 'Tonga' } },
  { iso3: 'TTO', iso2: 'TT', name: { en: 'Trinidad and Tobago', it: 'Trinidad e Tobago', es: 'Trinidad y Tobago' } },
  { iso3: 'TUN', iso2: 'TN', name: { en: 'Tunisia', it: 'Tunisia', es: 'Tunez' } },
  { iso3: 'TUR', iso2: 'TR', name: { en: 'Turkey', it: 'Turchia', es: 'Turquia' } },
  { iso3: 'TKM', iso2: 'TM', name: { en: 'Turkmenistan', it: 'Turkmenistan', es: 'Turkmenistan' } },
  { iso3: 'TUV', iso2: 'TV', name: { en: 'Tuvalu', it: 'Tuvalu', es: 'Tuvalu' } },
  { iso3: 'UGA', iso2: 'UG', name: { en: 'Uganda', it: 'Uganda', es: 'Uganda' } },
  { iso3: 'UKR', iso2: 'UA', name: { en: 'Ukraine', it: 'Ucraina', es: 'Ucrania' } },
  { iso3: 'ARE', iso2: 'AE', name: { en: 'United Arab Emirates', it: 'Emirati Arabi Uniti', es: 'Emiratos Arabes Unidos' } },
  { iso3: 'GBR', iso2: 'GB', name: { en: 'United Kingdom', it: 'Regno Unito', es: 'Reino Unido' } },
  { iso3: 'USA', iso2: 'US', name: { en: 'United States', it: 'Stati Uniti', es: 'Estados Unidos' } },
  { iso3: 'URY', iso2: 'UY', name: { en: 'Uruguay', it: 'Uruguay', es: 'Uruguay' } },
  { iso3: 'UZB', iso2: 'UZ', name: { en: 'Uzbekistan', it: 'Uzbekistan', es: 'Uzbekistan' } },
  { iso3: 'VUT', iso2: 'VU', name: { en: 'Vanuatu', it: 'Vanuatu', es: 'Vanuatu' } },
  { iso3: 'VAT', iso2: 'VA', name: { en: 'Vatican City', it: 'Citta del Vaticano', es: 'Ciudad del Vaticano' } },
  { iso3: 'VEN', iso2: 'VE', name: { en: 'Venezuela', it: 'Venezuela', es: 'Venezuela' } },
  { iso3: 'VNM', iso2: 'VN', name: { en: 'Vietnam', it: 'Vietnam', es: 'Vietnam' } },
  { iso3: 'YEM', iso2: 'YE', name: { en: 'Yemen', it: 'Yemen', es: 'Yemen' } },
  { iso3: 'ZMB', iso2: 'ZM', name: { en: 'Zambia', it: 'Zambia', es: 'Zambia' } },
  { iso3: 'ZWE', iso2: 'ZW', name: { en: 'Zimbabwe', it: 'Zimbabwe', es: 'Zimbabue' } },
  // Additional territories and smaller states
  { iso3: 'ABW', iso2: 'AW', name: { en: 'Aruba', it: 'Aruba', es: 'Aruba' } },
  { iso3: 'ALA', iso2: 'AX', name: { en: 'Aland Islands', it: 'Isole Aland', es: 'Islas Aland' } },
  { iso3: 'ASM', iso2: 'AS', name: { en: 'American Samoa', it: 'Samoa Americane', es: 'Samoa Americana' } },
  { iso3: 'AIA', iso2: 'AI', name: { en: 'Anguilla', it: 'Anguilla', es: 'Anguila' } },
  { iso3: 'ATA', iso2: 'AQ', name: { en: 'Antarctica', it: 'Antartide', es: 'Antartida' } },
  { iso3: 'BES', iso2: 'BQ', name: { en: 'Bonaire, Sint Eustatius and Saba', it: 'Bonaire, Sint Eustatius e Saba', es: 'Bonaire, San Eustaquio y Saba' } },
  { iso3: 'BVT', iso2: 'BV', name: { en: 'Bouvet Island', it: 'Isola Bouvet', es: 'Isla Bouvet' } },
  { iso3: 'IOT', iso2: 'IO', name: { en: 'British Indian Ocean Territory', it: 'Territorio Britannico dell\'Oceano Indiano', es: 'Territorio Britanico del Oceano Indico' } },
  { iso3: 'CYM', iso2: 'KY', name: { en: 'Cayman Islands', it: 'Isole Cayman', es: 'Islas Caiman' } },
  { iso3: 'CXR', iso2: 'CX', name: { en: 'Christmas Island', it: 'Isola di Natale', es: 'Isla de Navidad' } },
  { iso3: 'CCK', iso2: 'CC', name: { en: 'Cocos (Keeling) Islands', it: 'Isole Cocos', es: 'Islas Cocos' } },
  { iso3: 'COK', iso2: 'CK', name: { en: 'Cook Islands', it: 'Isole Cook', es: 'Islas Cook' } },
  { iso3: 'CUW', iso2: 'CW', name: { en: 'Curacao', it: 'Curacao', es: 'Curazao' } },
  { iso3: 'FLK', iso2: 'FK', name: { en: 'Falkland Islands', it: 'Isole Falkland', es: 'Islas Malvinas' } },
  { iso3: 'FRO', iso2: 'FO', name: { en: 'Faroe Islands', it: 'Isole Faroe', es: 'Islas Feroe' } },
  { iso3: 'GUF', iso2: 'GF', name: { en: 'French Guiana', it: 'Guyana Francese', es: 'Guayana Francesa' } },
  { iso3: 'PYF', iso2: 'PF', name: { en: 'French Polynesia', it: 'Polinesia Francese', es: 'Polinesia Francesa' } },
  { iso3: 'ATF', iso2: 'TF', name: { en: 'French Southern Territories', it: 'Terre Australi Francesi', es: 'Tierras Australes Francesas' } },
  { iso3: 'GIB', iso2: 'GI', name: { en: 'Gibraltar', it: 'Gibilterra', es: 'Gibraltar' } },
  { iso3: 'GRL', iso2: 'GL', name: { en: 'Greenland', it: 'Groenlandia', es: 'Groenlandia' } },
  { iso3: 'GLP', iso2: 'GP', name: { en: 'Guadeloupe', it: 'Guadalupa', es: 'Guadalupe' } },
  { iso3: 'GUM', iso2: 'GU', name: { en: 'Guam', it: 'Guam', es: 'Guam' } },
  { iso3: 'HKG', iso2: 'HK', name: { en: 'Hong Kong', it: 'Hong Kong', es: 'Hong Kong' } },
  { iso3: 'IMN', iso2: 'IM', name: { en: 'Isle of Man', it: 'Isola di Man', es: 'Isla de Man' } },
  { iso3: 'JEY', iso2: 'JE', name: { en: 'Jersey', it: 'Jersey', es: 'Jersey' } },
  { iso3: 'GGY', iso2: 'GG', name: { en: 'Guernsey', it: 'Guernsey', es: 'Guernsey' } },
  { iso3: 'XKX', iso2: 'XK', name: { en: 'Kosovo', it: 'Kosovo', es: 'Kosovo' } },
  { iso3: 'MAC', iso2: 'MO', name: { en: 'Macao', it: 'Macao', es: 'Macao' } },
  { iso3: 'MTQ', iso2: 'MQ', name: { en: 'Martinique', it: 'Martinica', es: 'Martinica' } },
  { iso3: 'MYT', iso2: 'YT', name: { en: 'Mayotte', it: 'Mayotte', es: 'Mayotte' } },
  { iso3: 'MSR', iso2: 'MS', name: { en: 'Montserrat', it: 'Montserrat', es: 'Montserrat' } },
  { iso3: 'NCL', iso2: 'NC', name: { en: 'New Caledonia', it: 'Nuova Caledonia', es: 'Nueva Caledonia' } },
  { iso3: 'NIU', iso2: 'NU', name: { en: 'Niue', it: 'Niue', es: 'Niue' } },
  { iso3: 'NFK', iso2: 'NF', name: { en: 'Norfolk Island', it: 'Isola Norfolk', es: 'Isla Norfolk' } },
  { iso3: 'MNP', iso2: 'MP', name: { en: 'Northern Mariana Islands', it: 'Isole Marianne Settentrionali', es: 'Islas Marianas del Norte' } },
  { iso3: 'PCN', iso2: 'PN', name: { en: 'Pitcairn', it: 'Pitcairn', es: 'Pitcairn' } },
  { iso3: 'PRI', iso2: 'PR', name: { en: 'Puerto Rico', it: 'Porto Rico', es: 'Puerto Rico' } },
  { iso3: 'REU', iso2: 'RE', name: { en: 'Reunion', it: 'Riunione', es: 'Reunion' } },
  { iso3: 'BLM', iso2: 'BL', name: { en: 'Saint Barthelemy', it: 'Saint-Barthelemy', es: 'San Bartolome' } },
  { iso3: 'SHN', iso2: 'SH', name: { en: 'Saint Helena', it: 'Sant\'Elena', es: 'Santa Elena' } },
  { iso3: 'MAF', iso2: 'MF', name: { en: 'Saint Martin', it: 'Saint Martin', es: 'San Martin' } },
  { iso3: 'SPM', iso2: 'PM', name: { en: 'Saint Pierre and Miquelon', it: 'Saint-Pierre e Miquelon', es: 'San Pedro y Miquelon' } },
  { iso3: 'SXM', iso2: 'SX', name: { en: 'Sint Maarten', it: 'Sint Maarten', es: 'Sint Maarten' } },
  { iso3: 'SGS', iso2: 'GS', name: { en: 'South Georgia', it: 'Georgia del Sud', es: 'Georgia del Sur' } },
  { iso3: 'SJM', iso2: 'SJ', name: { en: 'Svalbard and Jan Mayen', it: 'Svalbard e Jan Mayen', es: 'Svalbard y Jan Mayen' } },
  { iso3: 'TKL', iso2: 'TK', name: { en: 'Tokelau', it: 'Tokelau', es: 'Tokelau' } },
  { iso3: 'TCA', iso2: 'TC', name: { en: 'Turks and Caicos Islands', it: 'Isole Turks e Caicos', es: 'Islas Turcas y Caicos' } },
  { iso3: 'UMI', iso2: 'UM', name: { en: 'US Minor Outlying Islands', it: 'Isole Minori degli Stati Uniti', es: 'Islas Menores de Estados Unidos' } },
  { iso3: 'VIR', iso2: 'VI', name: { en: 'US Virgin Islands', it: 'Isole Vergini Americane', es: 'Islas Virgenes de EE.UU.' } },
  { iso3: 'VGB', iso2: 'VG', name: { en: 'British Virgin Islands', it: 'Isole Vergini Britanniche', es: 'Islas Virgenes Britanicas' } },
  { iso3: 'WLF', iso2: 'WF', name: { en: 'Wallis and Futuna', it: 'Wallis e Futuna', es: 'Wallis y Futuna' } },
  { iso3: 'ESH', iso2: 'EH', name: { en: 'Western Sahara', it: 'Sahara Occidentale', es: 'Sahara Occidental' } },
];

// Lookup maps for fast access
const iso3Map = new Map<string, CountryEntry>();
const iso2Map = new Map<string, CountryEntry>();
const nameMap = new Map<string, CountryEntry>();

for (const country of COUNTRIES) {
  iso3Map.set(country.iso3, country);
  iso2Map.set(country.iso2, country);
  nameMap.set(country.name.en.toLowerCase(), country);
}

export function getCountryByIso3(iso3: string): CountryEntry | undefined {
  return iso3Map.get(iso3.toUpperCase());
}

export function getCountryByIso2(iso2: string): CountryEntry | undefined {
  return iso2Map.get(iso2.toUpperCase());
}

export function getCountryByName(name: string): CountryEntry | undefined {
  return nameMap.get(name.toLowerCase());
}

export function getCountryName(iso3: string, lang: 'en' | 'it' | 'es' = 'en'): string {
  const entry = iso3Map.get(iso3.toUpperCase());
  return entry?.name[lang] ?? iso3;
}
